title: 'Intelligent Software & Natural Language Processing Laboratory'
url: 'https://nlpswkang.github.io'
baseurl: ''

update: 'Jan, 2020'

nav:
- name: 'Home'
  href: '#home'
- name: 'Members'
  href: '#about'
- name: 'Research'
  href: '#research'
- name: 'Projects'
  href: '#projects'
- name: 'Publications'
  href: '#publications'

data:
  home:
    title: 'Intelligent Software<br>&<br>Natural Language Processing Laboratory'
    text: ''
    social:
    - name: 'facebook'
      href: '#'
    - name: 'twitter'
      href: '#'
    - name: 'google-plus'
      href: '#'
    - name: 'linkedin'
      href: '#'
    - name: 'instagram'
      href: '#'
    - name: 'dribbble'
      href: '#'
    - name: 'skype'
      href: '#'

  about:
    name: 'Sangwoo Kang, Ph.D.'
    profile: 'profile_swkang_1.jpg'
    bio: He is an assistant professor in <b>the School of Computing at Gachon University</b> since September 2016. He got his Ph.D. in Computer Science at Sogang University, where he was also a Research Fellow Professor. His specialty is <b>Natural Language Processing</b>, and he is interested in spoken dialogue interface, information retrieval, text mining, opinion mining, big data, and UI/UX. His recent focus has been in applying <b>Deep Learning</b> techniques to his research. Currently, he is leading <b>Intelligent Software & Natural Language Processing Laboratory</b> at Gachon University.
    address: '#430 Main Library Building<br>1342 Seongnam-daero, Sujeong-gu, Seongnam-si, Gyeonggi-do<br>13120, Republic of Korea'
    phone: +82-031-750-8669
    email: swkang@gachon.ac.kr
  
  research:
  - title: Spoken Dialogue Interface / UI-UX / Natural Language Processing
    detail:
    - item: Dialogue System using (Deep) Machine Learning for Robot/Vehicle and Mobile
    - item: Dialogue and Discourse Management
    - item: Speech Acts / Action Classification
    - item: Name-entity Recognition
    - item: Post Correction for Automatic Speech Recognition
  - title: Question and Answering System
    detail:
    - item: Information Retrieval based Question and Answering
    - item: Knowledge based Question and Answering
    - item: Machine Reading Comprehension
  - title: Machine Transtlaion
    detail:
    - item: Multi-modal Neural Machine Translation
  - title: Opinion Mining
    detail:
    - item: Suggestion Mining
    - item: Sentimental Classification
     
  experience:
  - position: Assistant Professor
    department: Software
    school: Gachon University
    date: Aug 2016 ~ Present
  - position: Research Fellow Professor
    department: Computer Science
    school: Sogang University
    date: Feb 2013 ~ July 2016
  - position: Research Professor
    department: Computer Science and Engineering
    school: Sogang University
    date: Sep 2012 ~ Jan 2013
  - position: Instructor
    department: Computer Science and Engineering
    school: Sogang University
    date: Mar 2005 ~ Aug 2011

  professional-activities:
  - title: Program Committee Member
    detail:
    - item: Conference on Human & Cognitive Language Technology (2014 ~)
    - item: Korea Computer Congress (2015 ~)
  - title: 'Journal Reviewer'
    detail:
    - item: Pattern Recognition Letters (2009 ~)
    - item: AI Communications (2013 ~)
    - item: IEEE Access (2018 ~)
    - item: Sensors (2018 ~)
    
  awards:
  - title: 2017 국어정보처리 시스템 경진대회 대상 (문화체육관광부 장관상)
  - title: 2019 국어정보처리 시스템 경진대회 동상 (국립국어원장상)
  - title: 2020 국어정보처리 시스템 경진대회 대상 (문화체육관광부 장관상)

  teaching:
  - item: 'Robotics'
  - item: 'Computer Security'
  - item: 'Data Mining'
  - item: 'Web Programing'
  - item: 'Introduction of Artificial Intelligence'
  - item: 'Programming Basics'

  students: # 학생정보수정
  - name: 'Gyunyop Kim, MS student'
  - name: 'Sora Lee, MS student'
  - name: 'Eunseok Yoo, MS student'
  
  projects:
  - item: 2019 ~ Present, Principal Investigator, “Multi-modal Neural Machine Translation using Dependency Parsing,” Supported by National Research Foundation of Korea.
  - item: 2019 ~ Present, Principal Investigator, “사용자 적응형 어체 변환을 위한 데이터 구축 및 의미 표현 기술 연구,” Supported by Sogang University.
  - item: 2018 ~ 2019, Principal Investigator, “서비스 로봇을 위한 정보검색 질의응답(IR-QA) 시스템 개발,” Supported by Hyundai Motor.
  - item: 2017 ~ 2018, Principal Investigator, “유사도 측정 기법을 이용한 FAQ 시스템 개발,” Supported by Hyundai Motor.
  - item: 2017 ~ 2018, Principal Investigator, “영어사전용 식별 및 중의어 해소개발 기술,” Supported by Citrus EduTech.
  - item: 2017 ~ 2018, Principal Investigator, “사용자 적응형 어체 변환을 위한 형태소 합성 기술 연구,” Supported by Sogang University.
  - item: 2016 ~ Present, Principal Investigator, “Development of Intelligent Dialogue Interface for The IoT Environment,” Supported by National Research Foundation of Korea.
  - item: 2016 ~ 2018, Co-Principal Investigator, “Development of Distant Speech Recognition and Multi-Task Dialog Processing Technologies for In-Door Conversational Robots,” Supported by Ministry of Commerce, Industry and Energy.
  - item: 2013 ~ 2016, Principal Investigator, “The Technology Development of Dialogue Management for Virtual Personal Assistant Services of Smart devices,” Supported by National Research Foundation of Korea.
  - item: 2012 ~ 2015, Co-Principal Investigator (Chief Developer), “The Original Technology Development of Interactive Intelligent Personal Assistant Software for the Information Service on multiple domains,” Supported by Ministry of Knowledge Economy.
  - item: 2009 ~ 2013, Co-Principal Investigator (Chief Developer), “Developing Spoken Dialogue Interface Technologies or Intelligent Talking Companion Robots by Integrating Voice/Image Information and Workbench toolkits,” Supported by Ministry of Knowledge Economy.
  - item: 2011 ~ 2012, Researcher, “QA Solution for Personal information Using Wikipedia,” Supported by LG Electronics.
  - item: 2010 ~ 2012, Researcher, “Development of Speech Synthesizer and AAC Software for the Visually and Vocally impaired,” Supported by Ministry of Knowledge Economy
  - item: 2010 ~ 2010, Researcher, “Development of Word Suggestion Technology Considering Input Errors in Mobile Devices,” Supported by Samsung Electronics.
  - item: 2009 ~ 2012, Researcher, “Development of Intelligent Spoken Dialogue Interface for Mobile Devices,” Supported by National Research Foundation of Korea.
  - item: 2006 ~ 2009, Researcher, “The Development of Interaction Techniques for Intelligent Robots,” Supported by Ministry of Commerce, Industry and Energy.
  - item: 2006 ~ 2006, Researcher, “Technique Acceleration for SKT 1mm Service,” SK Telecom.
  - item: 2003 ~ 2006, Researcher, “The Development of Spoken Dialogue Interface Technique for Silver Mate,” Supported by Ministry of Commerce, Industry and Energy.
  - item: 2004 ~ 2006, Research Assistant, “The Development of a Machine Self Growth Model Based on Brain Information Processing,” Supported by Ministry of Commerce, Industry and Energy.
  - item: 2004 ~ 2004, Researcher, “The Development of a Multi Domain Dialogue Model for an Intelligent Robot System,” Supported by ETRI.
  - item: 2003 ~ 2005, Researcher, “A Study on Development of Dialog-based Information Retrieval and Question/Answering System based on Thesaurus,” Supported by Korea Science and Engineering Foundation.

  transfer:
  - item: 2015 ~ 2017, Co-Principal Investigator, “Dialogue Management and Language Understanding Technique for dialogue Interface in Vehicle Environment,” Hyundai Motor.
  - item: 2014, Co-Principal Investigator, “Spoken Dialogue Interface Technique for multi domain,” SK Telecom.

  patents:
  - item: 2018.09.04, Sangwoo Kang, “기계학습 모델을 이용한 자연어 생성 시스템, 방법, 및 컴퓨터 판독가능매체,” Domestic Patent
  - item: 2018.09.04, Sangwoo Kang, “개체명 인식 모델 생성 장치 및 방법,” Domestic Patent
  - item: 2018.04.03, Sangwoo Kang, “개체명 인식시스템, 방법, 및 컴퓨터 판독가능매체,” Domestic Patent
  - item: 2017.04.03, Sangwoo Kang et al., “지식베이스를 이용한 개체명 인식 코퍼스 생성 및 방법,” Domestic Patent
  - item: 2017.03.06, Sangwoo Kang et al., “문서 감정 분류용 딥러닝 인코딩 장치 및 방법,” Domestic Patent
  - item: 2017.02.27, Sangwoo Kang et al., “마이크로 블로그의 개체명 링킹 시스템,” Domestic Patent
  - item: 2016.01.27, Sangwoo Kang et al., “채팅 데이터 학습 및 서비스 방법 및 그에 따른 시스템,” Domestic Patent
  - item: 2015.12.24, Sangwoo Kang et al., “기계학습을 이용한 음성인식방법,” Domestic Patent
  - item: 2014, Sangwoo Kang et al., “Data Learning and Service Methods for a Chatting System,” International Patent Pending (PCT)
  - item: 2014, Sangwoo Kang et al., “Voice Recognition Method Using Machine Learning,” International Patent Pending (USA)

  publications:
  - title: Journal Publications
    list:
    - item: Yoonseok Heo, Sangwoo Kang(Corresponding Author), Jungyun Seo, (2020), "Hybrid Sense Classification Method for Large-scale Word Sense Disambiguation," IEEE Access, Vol.8(1).
      tag: SCIE
    - item: Yunyeong Yang, Sangwoo Kang(Corresponding Author), Jungyun Seo, (2020), "Improved Machine Reading Comprehension Using Data Validation For Weakly Labeled Data," IEEE Access, Vol.8(1).
      tag: SCIE
    - item: Yoonseok Heo, Sangwoo Kang(Corresponding Author), Jungyun Seo, (2019), "Multi-modal Neural Machine Translation with Weakly Labeled Images," IEEE Access, Vol.7(1).
      tag: SCIE
    - item: Youngmin Park, Sangwoo Kang(Corresponding Author), (2018), "Natural Language Generation using Dependency Tree Decoding for Spoken Dialog Systems," IEEE Access, Vol.7(1).
      tag: SCIE
    - item: Youngmin Park, Sangwoo Kang(Corresponding Author), Jungyun Seo (2018), "An Efficient Framework for Development of Task-Oriented Dialog Systems in a Smart Home Environment," Seonsors, Vol.18(5).
      tag: SCIE
    - item: Sangwoo Kang (2017), “Graph-Based Word Sense Disambiguation Using Iterative Approach,”Journal of Korean Institute of Next Generation Computing," (in Korean)
      tag: KCI
    - item: 'Sunjea Kwon, Juae Kim, Sangwoo Kang(Corresponding Author), Jungyun Seo (2017) “An Attention Method-based Deep Learning Encoder for the Sentiment Classification of Documents,” Journal of Korean Institute of Information Scientists and Engineers: Software and Applications. (in Korean)'
      tag: KCI
    - item: Youngmin Park, Yejin Kim, Sangwoo Kang(Corresponding Author), Jungyun Seo (2016), “Automatic Training Corpus Generation Method of Named Entity Recognition Using Knowledge-Bases," Cognitive Science, (in Korean)
      tag: KCI
    - item: Youngmin Park, Sangwoo Kang(corresponding author), Jungyun Seo (2016), “Information Extraction Using Distant Supervision and Semantic Similarities,” Advances in Electrical and Computer Engineering.
      tag: SCIE
    - item: Sunjae Kwon, Juae Kim, Sangwoo Kang(Corresponding Author), Jungyun Seo (2016), “Korean cQA system using Multiple Machine Learning Method,” Cognitive Science, (in Korean)
      tag: KCI
    - item: Dongsuk O, Sangwoo Kang(Corresponding Author), Jungyun Seo (2015), “An Iterative Approach to Subgraph-Based Word Sense Disambiguation Using Word2Vec,” Cognitive Science, (in Korean)
      tag: KCI
    - item: Soyun Jeong, Youngmin Park, Sangwoo Kang(Corresponding Author), Jungyun Seo (2015), “Entity Linking For Tweets Using User Model and Real-time News Stream,” Cognitive Science, Vol.26 No.4, pp.377-394. (in Korean)
      tag: KCI
    - item: Sangwoo Kang, Harksoo Kim, Hyun-Kyu Kang, Jungyun Seo (2014), “Lightweight Morphological Analysis Model for Smart Home Applications Based on Natural Language Interfaces,” International Journal of Distributed Sensor Networks, Vol.2014, Article ID 570634, pp.53-56.
      tag: SCIE
    - item: Sangwoo Kang, Jungyun Seo (2014), “Two-phase reanalysis model for understanding user intention,” Pattern Recognition Letters, Vol.42, pp.35-39.
      tag: SCIE
    - item: Sangwoo Kang, Ji-Hwan Kim, Jungyun Seo (2014), “Post-error Correction in Automatic Speech Recognition Using Discourse Information,” Advances in Electrical and Computer Engineering, Vol.14 No.2, pp.53-56.
      tag: SCIE
    - item: Sangwoo Kang, Youngjoong Ko, Jungyun Seo (2013), “Hierarchical speech-act classification for discourse analysis,” Pattern Recognition Letters, 34(10), pp.1119-1124.
      tag: SCIE
    - item: Sangwoo Kang, Youngjoong Ko, Jungyun Seo (2013), “A dialogue management system using a corpus-based framework and a dynamic dialogue transition model,” AI communications, Vol.26 No.2, pp.145-159.
      tag: SCIE
    - item: 'Sangwoo Kang, Jungyun Seo (2013), “An Integrated Model using Re-training Method for the Understanding of User Intention in a Dialogue System,” Journal of Korean Institute of Information Scientists and Engineers: Software and Applications, Vol.40 No.9, pp.519-525. (in Korean)'
      tag: KCI
    - item: Sangwoo Kang, Jeachul Yang, Jungyun Seo (2013), “Light Weight Korean Morphological Analysis Using Left-longest-match-preference model and Hidden Markov Model,” Cognitive Science, Vol24. No2., pp.95-109. (in Korean)
      tag: KCI
    - item: Sangwoo Kang, Youngjoong Ko, Jungyun Seo (2012), “Generating Effective Responses for a Plan-based Dialogue System in Human-Robot Interaction,” INFORMATION - An International Interdisciplinary Journal, International Information Institute, Vol.15 No.2, pp.949-960.
      tag: SCIE
    - item: Sangwoo Kang, Harksoo Kim, Jungyun Seo (2010), “A reliable multidomain model for speech act classification,” Pattern Recognition Letters, Vol.31 No.1, pp.71-74.
      tag: SCIE
    - item: Sangwoo Kang, Hongmin Park, Jungyun Seo (2010), “Emotion Classification of User's Utterance for a Dialogue System,” Cognitive Science, Vol.21 No.4, pp.459-480. (in Korean)
      tag: KCI
    - item: Choong-Nyoung Seon, Sangwoo Kang(Corresponding Author), Jungyun Seo (2010), “Automatic Recognition and Normalization System of Korean Time Expression using the individual time units,” Cognitive Science, Vol.21 No.4, pp.447-458. (in Korean)
      tag: KCI
    - item: Sangwoo kang, Sungwook Lee, Jungyun Seo (2009), “Dialogue Strategies to Overcome Speech Recognition Errors in Form-Filling Dialogue,” Lecture Note in Artificial Intelligence,” Vol.5459, pp.282-289.
      tag: 
    - item: Sangwoo Kang, Youngjoong Ko, Jungyun Seo (2008), “Using Plan Recognition and a Discourse Stack for Effective Response Generation in a Dialogue System,” Cognitive Science, Vol.19 No.2, pp.107-123. (in Korean)
      tag: KCI
    - item: Sangwoo Kang, Songwook Lee, Jungyun Seo (2006), “Dialogue Strategies to Overcome Speech Recognition Errors in Form-Filling Dialogue,” Cognitive Science, Vol.17 No.2, pp.139-150. (in Korean)
      tag: KCI
      
